// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db: tx,
	}
}

// User types
type User struct {
	Username     string
	AccountID    string
	PasswordHash string
	FirstName    string
	LastName     sql.NullString
	MiddleName   sql.NullString
	DisplayName  string
	IsAdmin      bool
	IsOnline     bool
	IsBlocked    bool
	Bio          string
	AvatarKey    sql.NullString
	CreatedAt    time.Time
	LastLogin    sql.NullTime
}

type ListUsersRow struct {
	Username    string
	AccountID   string
	DisplayName string
	IsAdmin     bool
	IsOnline    bool
	IsBlocked   bool
	Bio         string
	AvatarKey   sql.NullString
}

// RegistrationKey types
type RegistrationKey struct {
	Key      string
	CreatedAt time.Time
	IsActive bool
	UsedBy   sql.NullString
	UsedAt   sql.NullTime
}

// Message types
type Message struct {
	ID        string
	Sender    string
	Receiver  string
	Content   string
	Timestamp time.Time
	Type      string
	Edited    bool
	Deleted   bool
	Read      bool
	ReplyTo   sql.NullString
	Reactions interface{}
}

type GetRecentChatsRow struct {
	OtherUser string
	ID        string
	Sender    string
	Receiver  string
	Content   string
	Timestamp time.Time
	Type      string
	Edited    bool
	Deleted   bool
	Read      bool
	ReplyTo   sql.NullString
	Reactions interface{}
}

// Group types
type Group struct {
	ID          string
	Name        string
	Description sql.NullString
	Creator     string
	CreatedAt   time.Time
	Settings    interface{}
}

type GetGroupsWithMemberRow struct {
	ID             string
	Name           string
	Description    sql.NullString
	Creator        string
	CreatedAt      time.Time
	Settings       interface{}
	MemberUsername string
}

type GroupMessage struct {
	ID        string
	GroupID   string
	Sender    string
	Content   string
	Timestamp time.Time
	Type      string
	Edited    bool
	Deleted   bool
	ReplyTo   sql.NullString
	Reactions interface{}
}

// SupportMessage types
type SupportMessage struct {
	ID        string
	User      string
	Sender    string
	Content   string
	Timestamp time.Time
	Type      string
	Answered  bool
}

// User query params
type CreateUserParams struct {
	Username     string
	AccountID    string
	PasswordHash string
	FirstName    string
	LastName     sql.NullString
	MiddleName   sql.NullString
	DisplayName  string
	IsAdmin      bool
	Bio          string
}

type UpdateUserOnlineStatusParams struct {
	Username string
	Column2  bool
}

type UpdateUserBlockedParams struct {
	Username string
	Column2  bool
}

type UpdateUserBioParams struct {
	Bio      string
	Username string
}

type UpdateUserPasswordParams struct {
	Passwordhash string
	Username     string
}

type UpdateUserAvatarParams struct {
	AvatarKey sql.NullString
	Column2   bool
	Username  string
}

type ListUsersParams struct {
	Column1 bool
	Column2 sql.NullString
}

// Key query params
type UseRegistrationKeyParams struct {
	UsedBy  string
	Column2 string
}

// Message query params
type CreateMessageParams struct {
	ID       string
	Sender   string
	Receiver string
	Content  string
	Type     string
	ReplyTo  sql.NullString
}

type GetChatMessagesParams struct {
	Column1 string
	Column2 string
}

type UpdateMessageEditedParams struct {
	Content string
	Column2 string
}

type UpdateMessageReactionParams struct {
	Column2   string
	Reactions interface{}
}

// Group query params
type CreateGroupParams struct {
	ID          string
	Name        string
	Description sql.NullString
	Creator     string
	Settings    interface{}
}

type AddGroupMemberParams struct {
	GroupID  string
	Username string
}

type RemoveGroupMemberParams struct {
	GroupID  string
	Username string
}

type UpdateGroupSettingsParams struct {
	Settings interface{}
	Column2  string
}

type CreateGroupMessageParams struct {
	ID       string
	GroupID  string
	Sender   string
	Content  string
	Type     string
	ReplyTo  sql.NullString
}

type UpdateGroupMessageReactionParams struct {
	Column2   string
	Reactions interface{}
}

type UpdateGroupMessageEditedParams struct {
	Content string
	Column2 string
}

// Support query params
type CreateSupportMessageParams struct {
	ID      string
	User    string
	Sender  string
	Content string
	Type    string
}

// Stub implementations - these will be replaced by sqlc generate
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*User, error) {
	// TODO: generated by sqlc
	return nil, nil
}

func (q *Queries) UpdateUserLastLogin(ctx context.Context, username string) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) UpdateUserOnlineStatus(ctx context.Context, arg UpdateUserOnlineStatusParams) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) UpdateUserBlocked(ctx context.Context, arg UpdateUserBlockedParams) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) UpdateUserBio(ctx context.Context, arg UpdateUserBioParams) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	// TODO: generated by sqlc
	return nil, nil
}

func (q *Queries) ListAllUsers(ctx context.Context) ([]User, error) {
	// TODO: generated by sqlc
	return nil, nil
}

func (q *Queries) CreateRegistrationKey(ctx context.Context, key string) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) GetRegistrationKey(ctx context.Context, key string) (*RegistrationKey, error) {
	// TODO: generated by sqlc
	return nil, nil
}

func (q *Queries) UseRegistrationKey(ctx context.Context, arg UseRegistrationKeyParams) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) ListRegistrationKeys(ctx context.Context) ([]RegistrationKey, error) {
	// TODO: generated by sqlc
	return nil, nil
}

func (q *Queries) DeactivateRegistrationKey(ctx context.Context, key string) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) GetMessage(ctx context.Context, id string) (*Message, error) {
	// TODO: generated by sqlc
	return nil, nil
}

func (q *Queries) GetChatMessages(ctx context.Context, arg GetChatMessagesParams) ([]Message, error) {
	// TODO: generated by sqlc
	return nil, nil
}

func (q *Queries) GetSavedMessages(ctx context.Context, username string) ([]Message, error) {
	// TODO: generated by sqlc
	return nil, nil
}

func (q *Queries) GetRecentChats(ctx context.Context, username string) ([]GetRecentChatsRow, error) {
	// TODO: generated by sqlc
	return nil, nil
}

func (q *Queries) UpdateMessageRead(ctx context.Context, id string) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) UpdateMessageEdited(ctx context.Context, arg UpdateMessageEditedParams) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) UpdateMessageDeleted(ctx context.Context, id string) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) UpdateMessageReaction(ctx context.Context, arg UpdateMessageReactionParams) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) GetUnreadCount(ctx context.Context, username string) (int64, error) {
	// TODO: generated by sqlc
	return 0, nil
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) GetGroup(ctx context.Context, id string) (*Group, error) {
	// TODO: generated by sqlc
	return nil, nil
}

func (q *Queries) GetGroupsByCreator(ctx context.Context, creator string) ([]Group, error) {
	// TODO: generated by sqlc
	return nil, nil
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) GetGroupMembers(ctx context.Context, groupID string) ([]string, error) {
	// TODO: generated by sqlc
	return nil, nil
}

func (q *Queries) GetGroupsWithMember(ctx context.Context, username string) ([]GetGroupsWithMemberRow, error) {
	// TODO: generated by sqlc
	return nil, nil
}

func (q *Queries) UpdateGroupSettings(ctx context.Context, arg UpdateGroupSettingsParams) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) CreateGroupMessage(ctx context.Context, arg CreateGroupMessageParams) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) GetGroupMessage(ctx context.Context, id string) (*GroupMessage, error) {
	// TODO: generated by sqlc
	return nil, nil
}

func (q *Queries) GetGroupMessages(ctx context.Context, groupID string) ([]GroupMessage, error) {
	// TODO: generated by sqlc
	return nil, nil
}

func (q *Queries) UpdateGroupMessageReaction(ctx context.Context, arg UpdateGroupMessageReactionParams) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) UpdateGroupMessageEdited(ctx context.Context, arg UpdateGroupMessageEditedParams) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) UpdateGroupMessageDeleted(ctx context.Context, id string) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) CreateSupportMessage(ctx context.Context, arg CreateSupportMessageParams) error {
	// TODO: generated by sqlc
	return nil
}

func (q *Queries) GetSupportMessagesByUser(ctx context.Context, username string) ([]SupportMessage, error) {
	// TODO: generated by sqlc
	return nil, nil
}

func (q *Queries) GetAllSupportMessages(ctx context.Context) ([]SupportMessage, error) {
	// TODO: generated by sqlc
	return nil, nil
}

func (q *Queries) UpdateSupportMessageAnswered(ctx context.Context, id string) error {
	// TODO: generated by sqlc
	return nil
}
